alter session set nls_date_format = 'dd/mm/yyyy';

INSERT INTO artist VALUES(1, 'Kings of Leon', 'SUA');
INSERT INTO artist VALUES(2, 'Foo Fighters', 'SUA');
INSERT INTO artist VALUES(3, 'Eminem', 'SUA');
INSERT INTO artist VALUES(4, 'Tame Impala', 'Australia');
INSERT INTO artist VALUES(5, 'Muse', 'UK');
INSERT INTO artist VALUES(6, 'The Weeknd', 'Canada');
INSERT INTO artist VALUES(7, 'The 1975', 'UK');
INSERT INTO artist VALUES(8, 'Childish Gambino', 'SUA');
INSERT INTO artist VALUES(9, 'Maroon 5', 'SUA');
INSERT INTO artist VALUES(10, 'Mind Architect', 'Romania');
INSERT INTO artist VALUES(11, 'The Daily', 'SUA');
INSERT INTO artist VALUES(12, 'Loud Speakers Network', 'SUA');
INSERT INTO artist VALUES(13, 'The McElroys', 'SUA');

INSERT INTO album VALUES(1, 'Only By The Night', 1, 5);
INSERT INTO album VALUES(2, 'Mechanical Bull', 1, 3);
INSERT INTO album VALUES(3, 'The Eminem Show', 3, 3);
INSERT INTO album VALUES(4, 'Currents', 4, 4);
INSERT INTO album VALUES(5, 'The Slow Rush', 4, 2);
INSERT INTO album VALUES(6, 'Because the Internet', 8, 3);
INSERT INTO album VALUES(7, 'Camp', 8, 3);

INSERT INTO cantec VALUES(1, 'Closer', 1, 1, 237, 'Rock');
INSERT INTO cantec VALUES(2, 'Revelry', 1, 1, 201, 'Rock');
INSERT INTO cantec VALUES(3, 'Use Somebody', 1, 1, 230, 'Rock');
INSERT INTO cantec VALUES(4, '17', 1, 1, 185, 'Rock');
INSERT INTO cantec VALUES(5, 'Be Somebody', 1, 1, 227, 'Rock');
INSERT INTO cantec VALUES(6, 'Beautiful War', 1, 2, 309, 'Rock');
INSERT INTO cantec VALUES(7, 'Temple', 1, 2, 250, 'Rock');
INSERT INTO cantec VALUES(8, 'Wait for Me', 1, 2, 210, 'Rock');
INSERT INTO cantec VALUES(9, 'Without Me', 3, 3, 290, 'Rap');
INSERT INTO cantec VALUES(10, 'Business', 3, 3, 251, 'Rap');
INSERT INTO cantec VALUES(11, 'Superman', 3, 3, 350, 'Rap');
INSERT INTO cantec VALUES(12, 'The Less I Know The Better', 4, 4, 216, 'Indie');
INSERT INTO cantec VALUES(13, 'Let It Happen', 4, 4, 467, 'Indie');
INSERT INTO cantec VALUES(14, 'Love/Paranoia', 4, 4, 185, 'Indie');
INSERT INTO cantec VALUES(15, 'The Moment', 4, 4, 255, 'Indie');
INSERT INTO cantec VALUES(16, 'Is It True', 4, 5, 239, 'Indie');
INSERT INTO cantec VALUES(17, 'One More Hour', 4, 5, 432, 'Indie');
INSERT INTO cantec VALUES(18, '3005', 8, 6, 234, 'Hip-Hop');
INSERT INTO cantec VALUES(19, 'Sweatpants', 8, 6, 180, 'Hip-Hop');
INSERT INTO cantec VALUES(20, 'Flight of The Navigator', 8, 6, 344, 'Hip-Hop');
INSERT INTO cantec VALUES(21, 'Bonfire', 8, 7, 192, 'Hip-Hop');
INSERT INTO cantec VALUES(22, 'Heartbeat', 8, 7, 269, 'Hip-Hop');
INSERT INTO cantec VALUES(23, 'Les', 8, 7, 317, 'Hip-Hop');
INSERT INTO cantec VALUES(24, 'River', 3, null, 242, 'Rap');
INSERT INTO cantec VALUES(25, 'Best of You', 2, null, 255, 'Rock');
INSERT INTO cantec VALUES(26, 'Everlong', 2, null, 250, 'Rock');
INSERT INTO cantec VALUES(27, 'Uprising', 5, null, 304, 'Rock');
INSERT INTO cantec VALUES(28, 'Hysteria', 5, null, 227, 'Rock');
INSERT INTO cantec VALUES(29, 'Blinding Lights', 6, null, 200, 'Synthpop');
INSERT INTO cantec VALUES(30, 'Save Your Tears', 6, null, 215, 'Synthpop');
INSERT INTO cantec VALUES(31, 'Somebody Else', 7, null, 347, 'Synthpop');
INSERT INTO cantec VALUES(32, 'Whiskey', 9, null, 210, 'Pop');
INSERT INTO cantec VALUES(33, 'Denim Jacket', 9, null, 232, 'Pop');


INSERT INTO utilizator VALUES(1, 'Wakeham', 'Lauryn', 'lwakeham0@comcast.net', '21/04/1992');
INSERT INTO utilizator VALUES(2, 'Durdle', 'Gale', 'gdurdle1@netscape.com', '12/11/1999');
INSERT INTO utilizator VALUES(3, 'Jori', 'Cacilia', 'cjori2@goo.gl', '02/03/2001');
INSERT INTO utilizator VALUES(4, 'Partlett', 'Olag', 'opartlett3@topsy.com', '05/12/1998');
INSERT INTO utilizator VALUES(5, 'Dailly', 'Leola', 'ldailly4@gnu.org', '28/08/1997');
INSERT INTO utilizator VALUES(6, 'Sullens', 'Dianemarie', 'dsullens5@mashable.com', '27/07/1993');
INSERT INTO utilizator VALUES(7, 'Elmar', 'Hartley', 'helmar6@reddit.com', '20/04/1981');
INSERT INTO utilizator VALUES(8, 'Genike', 'Lynne', 'lgenike7@google.pl', '15/06/1990');
INSERT INTO utilizator VALUES(9, 'Wiggett', 'Cecil', 'cwiggett8@mlb.com', '08/05/1975');
INSERT INTO utilizator VALUES(10, 'Sisland', 'Giavani', 'gsisland9@blogspot.com', '24/10/2000');
INSERT INTO utilizator VALUES(11, 'Gallico', 'Lonna', 'lgallicoa@xrea.com', '13/02/1987');
INSERT INTO utilizator VALUES(12, 'Kidston', 'Larine', 'lkidstonb@vistaprint.com', '12/04/2003');
INSERT INTO utilizator VALUES(13, 'Clementson', 'Durward', 'dclementsonc@cafepress.com', '02/02/1991');
INSERT INTO utilizator VALUES(14, 'Donnelly', 'Dennet', 'ddonnellyd@gizmodo.com', '11/12/1998');
INSERT INTO utilizator VALUES(15, 'Carrane', 'Lonnard', 'lcarranee@eepurl.com', '02/01/1995');

INSERT INTO podcast VALUES(1, 'Cum ne crestem nivelul de fericire, o perspectiva evolutionista.', 10, 41*60+53, 'Educatie', 'Știai că, în creierul tău,  o opinie dezaprobatoare despre tine a cuiva din jurul tău are aceeași amprentă ca durerea fizică? Dar că trăim în perioada în care avem cele mai multe conexiuni sociale și cu toate astea ne simțim mai singuri ca oricând? Acestea sunt doar câteva dintre incompatibilitățile majore  între stilul nostru de viață actual și nevoile pentru care ne-am adaptat de-a lungul istoriei, pe care le discutăm în acest episod.');
INSERT INTO podcast VALUES(2, 'Creativitatea, o sclipire de moment sau un proces exersat?', 10, 30*60+23,'Educatie', 'In acest episod încercăm să îți aducem un “aha moment” despre cum funcționează “aha momentele” și cum să ai mai multe în viața ta de zi cu zi.');
INSERT INTO podcast VALUES(3, 'A Conversation With a Dogecoin Millionaire', 11, 37*60+25, 'Stiri', 'What started out as a kind of inside joke in the world of cryptocurrency has quickly become, for some, a very serious path to wealth. Today we explore the latest frenzy around a digital currency, what it tells us about the flaws in the old economy — and the risks and rewards of the new one.');
INSERT INTO podcast VALUES(4, 'Rural Tennessee’s Vaccine Hesitators', 11, 27*60+25, 'Stiri', 'Vaccine hesitancy is a major reason that many experts now fear the United States will struggle to attain herd immunity against the coronavirus.');
INSERT INTO podcast VALUES(5, 'A Major Ruling From Facebook’s ‘Supreme Court’', 11, 31*60+15, 'Stiri', 'Was Facebook right to indefinitely bar former President Donald J. Trump from the platform after the Capitol riot?');
INSERT INTO podcast VALUES(6, 'Too Old For This', 12, 21*60+15,'Comedie', 'Is a house party that''s also a block party...a blouse party?');
INSERT INTO podcast VALUES(7, 'Morgan Beeman Strikes Again', 13, 31*60+15,'Comedie', 'We thought it was high time to invite someone who’s actually smart to help us give advice; luckily Jean Grae agreed to be the newest McElroy brother. Jean is so smart that she had the foresight in high school to realize that the SATs are an outdated measurement built on a societal structure that values expedience, instead of like, a test that lets you drink wine and cry.');

INSERT INTO playlist VALUES(1, 'playlist1', 11, 3, '23/09/2020');
INSERT INTO playlist VALUES(2, 'cool songs', 5, 2, '13/04/2021');
INSERT INTO playlist VALUES(3, 'my songs', 11, 1, '26/09/2018');
INSERT INTO playlist VALUES(4, 'rock songs', 11, 6, '11/12/2013');
INSERT INTO playlist VALUES(5, 'playlist1', 3, 2, '06/02/2018');
INSERT INTO playlist VALUES(6, 'chill songs', 1, 3, '01/01/2017');
INSERT INTO playlist VALUES(7, 'Rap Songs', null, 4, '01/01/2010');
INSERT INTO playlist VALUES(8, 'Hip-Hop Songs', null, 4, '01/01/2010');
 
INSERT INTO utilizator_playlist VALUES(11, 1, '15/08/2019');
INSERT INTO utilizator_playlist VALUES(2, 4, '17/08/2019');
INSERT INTO utilizator_playlist VALUES(12, 1, '24/10/2019');
INSERT INTO utilizator_playlist VALUES(1, 2, '05/02/2020');
INSERT INTO utilizator_playlist VALUES(10, 5, '23/02/2020');
INSERT INTO utilizator_playlist VALUES(15, 4, '19/06/2020');
INSERT INTO utilizator_playlist VALUES(10, 4, '03/07/2020');
INSERT INTO utilizator_playlist VALUES(4, 2, '01/10/2020');
INSERT INTO utilizator_playlist VALUES(11, 6, '02/03/2021');
INSERT INTO utilizator_playlist VALUES(3, 3, '17/03/2021');
INSERT INTO utilizator_playlist VALUES(15, 3, '05/04/2021');
INSERT INTO utilizator_playlist VALUES(2, 2, '15/05/2021');
INSERT INTO utilizator_playlist VALUES(11, 5, '19/05/2021');
INSERT INTO utilizator_playlist VALUES(2, 5, '16/06/2021');

INSERT INTO utilizator_album VALUES(12, 7);
INSERT INTO utilizator_album VALUES(14, 4);
INSERT INTO utilizator_album VALUES(15, 1);
INSERT INTO utilizator_album VALUES(15, 7);
INSERT INTO utilizator_album VALUES(5, 1);
INSERT INTO utilizator_album VALUES(12, 3);
INSERT INTO utilizator_album VALUES(4, 2);
INSERT INTO utilizator_album VALUES(6, 7);
INSERT INTO utilizator_album VALUES(4, 5);
INSERT INTO utilizator_album VALUES(5, 6);
INSERT INTO utilizator_album VALUES(15, 3);
INSERT INTO utilizator_album VALUES(8, 2);
INSERT INTO utilizator_album VALUES(14, 2);
INSERT INTO utilizator_album VALUES(13, 5);

INSERT INTO utilizator_artist VALUES(3, 4);
INSERT INTO utilizator_artist VALUES(4, 6);
INSERT INTO utilizator_artist VALUES(14, 13);
INSERT INTO utilizator_artist VALUES(11, 8);
INSERT INTO utilizator_artist VALUES(1, 3);
INSERT INTO utilizator_artist VALUES(2, 11);
INSERT INTO utilizator_artist VALUES(2, 8);
INSERT INTO utilizator_artist VALUES(3, 3);
INSERT INTO utilizator_artist VALUES(4, 8);
INSERT INTO utilizator_artist VALUES(9, 7);
INSERT INTO utilizator_artist VALUES(11, 7);
INSERT INTO utilizator_artist VALUES(2, 10);
INSERT INTO utilizator_artist VALUES(7, 9);
INSERT INTO utilizator_artist VALUES(6, 7);
INSERT INTO utilizator_artist VALUES(7, 6);
INSERT INTO utilizator_artist VALUES(12, 11);
INSERT INTO utilizator_artist VALUES(3, 8);
INSERT INTO utilizator_artist VALUES(2, 3);
INSERT INTO utilizator_artist VALUES(13, 3);
INSERT INTO utilizator_artist VALUES(13, 12);
INSERT INTO utilizator_artist VALUES(7, 8);


INSERT INTO playlist_cantec VALUES(7,9);
INSERT INTO playlist_cantec VALUES(7,10);
INSERT INTO playlist_cantec VALUES(7,11);
INSERT INTO playlist_cantec VALUES(7,24);
INSERT INTO playlist_cantec VALUES(8,18);
INSERT INTO playlist_cantec VALUES(8,19);
INSERT INTO playlist_cantec VALUES(8,20);
INSERT INTO playlist_cantec VALUES(8,21);
INSERT INTO playlist_cantec VALUES(1, 32);
INSERT INTO playlist_cantec VALUES(1, 10);
INSERT INTO playlist_cantec VALUES(1, 19);
INSERT INTO playlist_cantec VALUES(2, 18);
INSERT INTO playlist_cantec VALUES(2, 13);
INSERT INTO playlist_cantec VALUES(3, 4);
INSERT INTO playlist_cantec VALUES(5, 19);
INSERT INTO playlist_cantec VALUES(5, 5);
INSERT INTO playlist_cantec VALUES(6, 8);
INSERT INTO playlist_cantec VALUES(6, 9);
INSERT INTO playlist_cantec VALUES(6, 31);
INSERT INTO playlist_cantec VALUES(4, 2);
INSERT INTO playlist_cantec VALUES(4, 3);
INSERT INTO playlist_cantec VALUES(4, 4);
INSERT INTO playlist_cantec VALUES(4, 25);
INSERT INTO playlist_cantec VALUES(4, 26);
INSERT INTO playlist_cantec VALUES(4, 28);


INSERT INTO utilizator_cantec VALUES(1, 28, '02/12/2019', 1 , 5);
INSERT INTO utilizator_cantec VALUES(15, 21, '02/04/2021', 1 , 9);
INSERT INTO utilizator_cantec VALUES(13, 27, '20/05/2020', 1 , 3);
INSERT INTO utilizator_cantec VALUES(12, 13, '02/12/2019', -1 , 6);
INSERT INTO utilizator_cantec VALUES(14, 16, null, null , 10);
INSERT INTO utilizator_cantec VALUES(3, 13, null, null , 2);
INSERT INTO utilizator_cantec VALUES(12, 28, null, null , 5);
INSERT INTO utilizator_cantec VALUES(8, 3, '27/04/2021', -1 , 10);
INSERT INTO utilizator_cantec VALUES(3, 25, null, null , 3);
INSERT INTO utilizator_cantec VALUES(8, 12, null, null , 2);
INSERT INTO utilizator_cantec VALUES(8, 18, '06/06/2020', -1 , 6);
INSERT INTO utilizator_cantec VALUES(10, 24, '06/06/2020', 1 , 4);
INSERT INTO utilizator_cantec VALUES(15, 14, '12/07/2019', 1 , 3);
INSERT INTO utilizator_cantec VALUES(6, 8, '06/06/2020', 1 , 2);
INSERT INTO utilizator_cantec VALUES(7, 16, null, null , 10);
INSERT INTO utilizator_cantec VALUES(6, 23, '03/10/2019', -1 , 5);
INSERT INTO utilizator_cantec VALUES(13, 32, '27/04/2021', 1 , 2);
INSERT INTO utilizator_cantec VALUES(14, 12, '30/10/2019', -1 , 1);
INSERT INTO utilizator_cantec VALUES(12, 21, null, null , 2);
INSERT INTO utilizator_cantec VALUES(9, 1, '19/05/2019', 1 , 10);
INSERT INTO utilizator_cantec VALUES(9, 7, '19/05/2019', -1 , 8);
INSERT INTO utilizator_cantec VALUES(2, 1, null, null , 4);
INSERT INTO utilizator_cantec VALUES(5, 33, '10/11/2020', 1 , 5);
INSERT INTO utilizator_cantec VALUES(8, 26, null, null , 6);
INSERT INTO utilizator_cantec VALUES(9, 25, '28/12/2019', 1 , 6);
INSERT INTO utilizator_cantec VALUES(11, 22, '20/05/2020', 1 , 1);
INSERT INTO utilizator_cantec VALUES(1, 17, '13/08/2019', -1 , 3);
INSERT INTO utilizator_cantec VALUES(1, 32, '29/07/2020', 1 , 5);
INSERT INTO utilizator_cantec VALUES(12, 11, '12/07/2019', 1 , 4);
INSERT INTO utilizator_cantec VALUES(12, 17, null, null , 2);
INSERT INTO utilizator_cantec VALUES(6, 31, '27/04/2021', 1 , 3);
INSERT INTO utilizator_cantec VALUES(14, 8, '28/12/2019', -1 , 10);
INSERT INTO utilizator_cantec VALUES(9, 3, '25/05/2020', 1 , 7);
INSERT INTO utilizator_cantec VALUES(4, 22, null, null , 9);
INSERT INTO utilizator_cantec VALUES(10, 13, null, null , 10);
INSERT INTO utilizator_cantec VALUES(11, 12, '11/11/2019', 1 , 3);
INSERT INTO utilizator_cantec VALUES(3, 29, '02/04/2021', 1 , 10);
INSERT INTO utilizator_cantec VALUES(8, 28, '15/03/2020', 1 , 6);
INSERT INTO utilizator_cantec VALUES(2, 15, null, null , 7);
INSERT INTO utilizator_cantec VALUES(13, 15, '03/10/2019', -1 , 8);

INSERT INTO utilizator_podcast VALUES(4, 4, 1);
INSERT INTO utilizator_podcast VALUES(2, 4, null);
INSERT INTO utilizator_podcast VALUES(5, 5, 1);
INSERT INTO utilizator_podcast VALUES(4, 3, 1);
INSERT INTO utilizator_podcast VALUES(3, 7, null);
INSERT INTO utilizator_podcast VALUES(6, 4, 1);
INSERT INTO utilizator_podcast VALUES(5, 7, null);
INSERT INTO utilizator_podcast VALUES(2, 3, -1);
INSERT INTO utilizator_podcast VALUES(3, 3, -1);
INSERT INTO utilizator_podcast VALUES(13, 6, 1);
INSERT INTO utilizator_podcast VALUES(7, 2, -1);
INSERT INTO utilizator_podcast VALUES(5, 3,  1);
INSERT INTO utilizator_podcast VALUES(12, 5, 1);
INSERT INTO utilizator_podcast VALUES(14, 2, 1);
INSERT INTO utilizator_podcast VALUES(9, 1, null);